// Canonical aisle/category set. Order here is the default store layout used
// until the household customizes `aisleOrder` in the shared doc.
export const CATEGORIES = [
  "Produce",
  "Bakery",
  "Meat & Seafood",
  "Dairy & Eggs",
  "Frozen",
  "Pantry & Baking",
  "Beverages",
  "Snacks",
  "Household",
  "Personal Care",
  "Other",
] as const;

export type Category = (typeof CATEGORIES)[number];

export const DEFAULT_AISLES: Category[] = [...CATEGORIES];

export const FALLBACK_CATEGORY: Category = "Other";

// A language pack maps a Category to the list of keywords (already normalized:
// lowercase, singular-ish) that should resolve to it. Matching is substring
// based, so "organic whole milk" matches the keyword "milk".
//
// The table is intentionally a plain data structure so additional languages can
// be dropped in (see LANGUAGES below) without touching the resolver logic.
export type LanguagePack = Record<Category, string[]>;

const en: LanguagePack = {
  Produce: [
    "apple",
    "banana",
    "orange",
    "lemon",
    "lime",
    "grape",
    "berry",
    "strawberr",
    "blueberr",
    "raspberr",
    "melon",
    "watermelon",
    "mango",
    "pineapple",
    "peach",
    "pear",
    "plum",
    "cherry",
    "kiwi",
    "avocado",
    "tomato",
    "potato",
    "onion",
    "garlic",
    "carrot",
    "celery",
    "lettuce",
    "spinach",
    "kale",
    "broccoli",
    "cauliflower",
    "cucumber",
    "pepper",
    "zucchini",
    "squash",
    "mushroom",
    "corn",
    "pea",
    "bean sprout",
    "cabbage",
    "ginger",
    "herb",
    "basil",
    "cilantro",
    "parsley",
    "mint",
    "fruit",
    "vegetable",
    "veggie",
    "salad",
    "scallion",
    "leek",
    "radish",
    "beet",
    "asparagus",
    "eggplant",
  ],
  Bakery: [
    "bread",
    "bagel",
    "baguette",
    "roll",
    "bun",
    "croissant",
    "muffin",
    "tortilla",
    "pita",
    "naan",
    "cake",
    "pastry",
    "donut",
    "doughnut",
    "brioche",
    "ciabatta",
    "sourdough",
    "pretzel",
    "cornbread",
    "biscuit",
  ],
  "Meat & Seafood": [
    "chicken",
    "beef",
    "pork",
    "lamb",
    "turkey",
    "bacon",
    "sausage",
    "ham",
    "steak",
    "mince",
    "ground beef",
    "ribs",
    "salami",
    "prosciutto",
    "chorizo",
    "fish",
    "salmon",
    "tuna",
    "shrimp",
    "prawn",
    "cod",
    "tilapia",
    "crab",
    "lobster",
    "clam",
    "mussel",
    "oyster",
    "scallop",
    "seafood",
    "meat",
    "hot dog",
    "deli",
    "veal",
  ],
  "Dairy & Eggs": [
    "milk",
    "cheese",
    "yogurt",
    "yoghurt",
    "butter",
    "cream",
    "egg",
    "kefir",
    "cottage cheese",
    "sour cream",
    "margarine",
    "mozzarella",
    "cheddar",
    "parmesan",
    "feta",
    "brie",
    "gouda",
    "creamer",
    "buttermilk",
    "ghee",
  ],
  Frozen: [
    "frozen",
    "ice cream",
    "popsicle",
    "gelato",
    "sorbet",
    "frozen pizza",
    "fish stick",
    "frozen veg",
    "frozen fruit",
    "freezer",
    "ice pack",
    "ice",
  ],
  "Pantry & Baking": [
    "flour",
    "sugar",
    "salt",
    "rice",
    "pasta",
    "noodle",
    "spaghetti",
    "oil",
    "olive oil",
    "vinegar",
    "sauce",
    "ketchup",
    "mustard",
    "mayo",
    "mayonnaise",
    "soy sauce",
    "honey",
    "jam",
    "jelly",
    "peanut butter",
    "cereal",
    "oat",
    "oatmeal",
    "granola",
    "lentil",
    "chickpea",
    "canned",
    "can of",
    "soup",
    "broth",
    "stock",
    "tomato sauce",
    "tomato paste",
    "spice",
    "cinnamon",
    "pepper corn",
    "baking soda",
    "baking powder",
    "yeast",
    "vanilla",
    "cocoa",
    "chocolate chip",
    "syrup",
    "molasses",
    "cornstarch",
    "breadcrumb",
    "stuffing",
    "couscous",
    "quinoa",
    "tortilla chip",
    "taco",
    "curry",
    "coconut milk",
    "tahini",
    "raisin",
    "nut",
    "almond",
    "walnut",
    "cashew",
    "seed",
    "tofu",
    "ramen",
    "gravy",
    "salsa",
    "pickle",
    "olive",
    "relish",
    "bouillon",
  ],
  Beverages: [
    "water",
    "juice",
    "soda",
    "cola",
    "coffee",
    "tea",
    "beer",
    "wine",
    "drink",
    "lemonade",
    "smoothie",
    "kombucha",
    "sparkling",
    "tonic",
    "energy drink",
    "sports drink",
    "cider",
    "champagne",
    "liquor",
    "whiskey",
    "vodka",
    "gin",
    "rum",
    "espresso",
    "cappuccino",
    "milkshake",
  ],
  Snacks: [
    "chip",
    "crisp",
    "cracker",
    "popcorn",
    "pretzel snack",
    "candy",
    "chocolate",
    "cookie",
    "biscuit snack",
    "snack",
    "nuts mix",
    "trail mix",
    "granola bar",
    "protein bar",
    "gum",
    "jerky",
    "fruit snack",
    "wafer",
    "marshmallow",
  ],
  Household: [
    "paper towel",
    "toilet paper",
    "tissue",
    "napkin",
    "trash bag",
    "garbage bag",
    "detergent",
    "dish soap",
    "dishwasher",
    "cleaner",
    "bleach",
    "sponge",
    "foil",
    "aluminum foil",
    "plastic wrap",
    "cling film",
    "zip bag",
    "ziploc",
    "battery",
    "light bulb",
    "candle",
    "laundry",
    "fabric softener",
    "air freshener",
    "broom",
    "mop",
    "bucket",
    "glove",
    "matches",
    "lighter",
    "wrap",
  ],
  "Personal Care": [
    "shampoo",
    "conditioner",
    "soap",
    "body wash",
    "toothpaste",
    "toothbrush",
    "floss",
    "deodorant",
    "razor",
    "shaving",
    "lotion",
    "moisturizer",
    "sunscreen",
    "makeup",
    "cosmetic",
    "tampon",
    "pad",
    "diaper",
    "wipe",
    "cotton",
    "q-tip",
    "mouthwash",
    "hand sanitizer",
    "vitamin",
    "medicine",
    "bandage",
    "band-aid",
    "ibuprofen",
    "aspirin",
    "tissue paper",
    "perfume",
    "hair gel",
    "nail",
  ],
  Other: [],
};

// German keyword pack — maps the same canonical (English) category keys to
// German grocery keywords, so a German-speaking user's items categorize too.
const de: LanguagePack = {
  Produce: [
    "apfel",
    "äpfel",
    "banane",
    "birne",
    "orange",
    "mandarine",
    "clementine",
    "zitrone",
    "limette",
    "grapefruit",
    "traube",
    "weintraube",
    "erdbeere",
    "himbeere",
    "heidelbeere",
    "blaubeere",
    "brombeere",
    "kirsche",
    "pflaume",
    "pfirsich",
    "nektarine",
    "aprikose",
    "ananas",
    "mango",
    "melone",
    "wassermelone",
    "kiwi",
    "avocado",
    "tomate",
    "gurke",
    "paprika",
    "karotte",
    "möhre",
    "kartoffel",
    "zwiebel",
    "knoblauch",
    "lauch",
    "porree",
    "sellerie",
    "salat",
    "kopfsalat",
    "rucola",
    "spinat",
    "kohl",
    "brokkoli",
    "blumenkohl",
    "zucchini",
    "aubergine",
    "kürbis",
    "pilz",
    "champignon",
    "rettich",
    "radieschen",
    "rote bete",
    "spargel",
    "bohne",
    "erbse",
    "mais",
    "ingwer",
    "petersilie",
    "basilikum",
    "kräuter",
    "obst",
    "gemüse",
  ],
  Bakery: [
    "brot",
    "brötchen",
    "semmel",
    "weckle",
    "baguette",
    "ciabatta",
    "toast",
    "toastbrot",
    "vollkornbrot",
    "knäckebrot",
    "croissant",
    "hörnchen",
    "brezel",
    "brezn",
    "laugengebäck",
    "kuchen",
    "torte",
    "muffin",
    "donut",
    "berliner",
    "krapfen",
    "plunder",
    "blätterteig",
    "hefeteig",
    "stollen",
    "lebkuchen",
    "keks",
    "gebäck",
    "zwieback",
    "waffel",
    "kaiserbrötchen",
    "fladenbrot",
    "pita",
    "naan",
    "tortilla",
    "wrap",
    "roggenbrot",
    "dinkelbrot",
    "sonnenblumenbrot",
    "mehrkornbrot",
    "backwaren",
    "donauwelle",
    "bienenstich",
  ],
  "Meat & Seafood": [
    "fleisch",
    "hähnchen",
    "hühnchen",
    "huhn",
    "pute",
    "putenbrust",
    "hähnchenbrust",
    "rind",
    "rindfleisch",
    "hackfleisch",
    "gehacktes",
    "schwein",
    "schweinefleisch",
    "kotelett",
    "schnitzel",
    "steak",
    "braten",
    "gulasch",
    "wurst",
    "bratwurst",
    "currywurst",
    "salami",
    "schinken",
    "speck",
    "bacon",
    "wiener",
    "frikadelle",
    "leberkäse",
    "lamm",
    "kalb",
    "ente",
    "gans",
    "fisch",
    "lachs",
    "thunfisch",
    "forelle",
    "hering",
    "kabeljau",
    "scholle",
    "garnele",
    "shrimp",
    "krabbe",
    "muschel",
    "tintenfisch",
    "meeresfrüchte",
    "räucherlachs",
    "matjes",
    "aufschnitt",
  ],
  "Dairy & Eggs": [
    "milch",
    "vollmilch",
    "buttermilch",
    "haltbarmilch",
    "joghurt",
    "jogurt",
    "quark",
    "sahne",
    "schlagsahne",
    "schmand",
    "crème fraîche",
    "creme fraiche",
    "butter",
    "margarine",
    "käse",
    "gouda",
    "edamer",
    "emmentaler",
    "mozzarella",
    "frischkäse",
    "hüttenkäse",
    "parmesan",
    "feta",
    "camembert",
    "brie",
    "harzer",
    "ricotta",
    "mascarpone",
    "eier",
    "kefir",
    "pudding",
    "skyr",
    "molke",
    "dickmilch",
    "milchreis",
    "rahm",
    "käseaufschnitt",
    "streichkäse",
  ],
  Frozen: [
    "tiefkühl",
    "tk-",
    "gefroren",
    "eis",
    "speiseeis",
    "eiscreme",
    "tiefkühlpizza",
    "tk-pizza",
    "pommes",
    "fischstäbchen",
    "rahmspinat",
    "tiefkühlgemüse",
    "tk-gemüse",
    "tiefkühlobst",
    "gefriergut",
    "eis am stiel",
    "tiefkühlkost",
    "schlemmerfilet",
    "tk-beeren",
    "eiswürfel",
    "tiefkühlbeeren",
    "tk-kräuter",
    "frostgemüse",
    "tiefkühlfisch",
  ],
  "Pantry & Baking": [
    "mehl",
    "zucker",
    "puderzucker",
    "vanillezucker",
    "salz",
    "pfeffer",
    "gewürz",
    "öl",
    "olivenöl",
    "sonnenblumenöl",
    "essig",
    "balsamico",
    "reis",
    "nudel",
    "nudeln",
    "pasta",
    "spaghetti",
    "penne",
    "couscous",
    "bulgur",
    "linse",
    "kichererbse",
    "konserve",
    "dose",
    "tomatenmark",
    "passierte tomaten",
    "brühe",
    "suppe",
    "soße",
    "sauce",
    "ketchup",
    "senf",
    "mayonnaise",
    "honig",
    "marmelade",
    "konfitüre",
    "nutella",
    "nuss-nougat",
    "haferflocken",
    "müsli",
    "cornflakes",
    "backpulver",
    "hefe",
    "vanille",
    "kakao",
    "stärke",
    "grieß",
    "polenta",
    "tomatensoße",
    "pesto",
    "gewürze",
  ],
  Beverages: [
    "wasser",
    "mineralwasser",
    "sprudel",
    "saft",
    "apfelsaft",
    "orangensaft",
    "fruchtsaft",
    "schorle",
    "limonade",
    "limo",
    "cola",
    "fanta",
    "sprite",
    "spezi",
    "eistee",
    "tee",
    "kaffee",
    "espresso",
    "bier",
    "pils",
    "weizen",
    "wein",
    "rotwein",
    "weißwein",
    "sekt",
    "prosecco",
    "champagner",
    "energydrink",
    "energy drink",
    "smoothie",
    "sirup",
    "tonic",
    "spirituose",
    "schnaps",
    "wodka",
    "whisky",
    "rum",
    "likör",
    "getränk",
    "softdrink",
    "radler",
  ],
  Snacks: [
    "chips",
    "knabber",
    "knabberei",
    "erdnuss",
    "erdnüsse",
    "nuss",
    "nüsse",
    "cashew",
    "mandel",
    "pistazie",
    "popcorn",
    "cracker",
    "salzstange",
    "schokolade",
    "schokoriegel",
    "riegel",
    "praline",
    "bonbon",
    "gummibärchen",
    "fruchtgummi",
    "lakritz",
    "lutscher",
    "kaugummi",
    "müsliriegel",
    "kekse",
    "waffeln",
    "tortilla chips",
    "nachos",
    "studentenfutter",
    "trockenfrüchte",
    "rosine",
    "süßigkeit",
    "naschen",
    "schokokuss",
    "marshmallow",
    "toffee",
    "karamell",
  ],
  Household: [
    "spülmittel",
    "geschirrspül",
    "spülmaschinentab",
    "waschmittel",
    "weichspüler",
    "reiniger",
    "allzweckreiniger",
    "putzmittel",
    "wc-reiniger",
    "klobürste",
    "schwamm",
    "putzlappen",
    "müllbeutel",
    "müllsack",
    "alufolie",
    "frischhaltefolie",
    "backpapier",
    "küchenrolle",
    "küchenpapier",
    "toilettenpapier",
    "klopapier",
    "taschentücher",
    "servietten",
    "kerze",
    "batterie",
    "glühbirne",
    "streichholz",
    "feuerzeug",
    "putztuch",
    "scheuermilch",
    "entkalker",
    "fleckentferner",
    "lufterfrischer",
    "gefrierbeutel",
    "haushaltshandschuh",
    "wäscheklammer",
    "putzeimer",
    "staubtuch",
    "mikrofasertuch",
  ],
  "Personal Care": [
    "shampoo",
    "spülung",
    "haarspülung",
    "duschgel",
    "seife",
    "handseife",
    "zahnpasta",
    "zahncreme",
    "zahnbürste",
    "zahnseide",
    "mundwasser",
    "deo",
    "deodorant",
    "rasierer",
    "rasierschaum",
    "rasiergel",
    "rasierklinge",
    "creme",
    "handcreme",
    "bodylotion",
    "gesichtscreme",
    "sonnencreme",
    "windel",
    "feuchttücher",
    "wattepad",
    "wattestäbchen",
    "tampon",
    "binde",
    "damenbinde",
    "slipeinlage",
    "haarspray",
    "haargel",
    "haarfarbe",
    "parfüm",
    "lippenpflege",
    "lippenstift",
    "wimperntusche",
    "make-up",
    "nagellack",
    "pflaster",
    "desinfektionsmittel",
  ],
  Other: [],
};

export const LANGUAGES: Record<string, LanguagePack> = { en, de };

export const DEFAULT_LANGUAGE = "en";
